/*
 * pgl_mobile_extensions.c - Static extension registry for mobile platforms
 *
 * On mobile platforms (iOS/Android), we cannot use dlopen/dlsym to dynamically
 * load extensions because:
 * - iOS prohibits code loading at runtime
 * - Android has restrictions and complexity with native library loading
 *
 * Instead, we compile extension code directly into libpglite and provide a
 * static registry that maps function names to their addresses.
 *
 * EXTERNAL EXTENSION SUPPORT:
 * This file provides weak hooks that can be overridden by app-generated code
 * to add additional extension registries. The Expo config plugin generates
 * a pgl_extension_registry.c file that implements these hooks to register
 * extension functions from packages like @react-native-pglite/postgis.
 *
 * LINKER INTEGRATION:
 * The pgl_mobile_force_link_extensions() function creates explicit references
 * to all extension functions. This function MUST be called from somewhere in
 * the main code path (e.g., during PostgreSQL initialization) to ensure the
 * linker includes the extension object files from the static archive.
 * Without this, the linker would see the symbol table (with function pointers)
 * but not realize it needs to include the actual function implementations.
 *
 * To add a new extension:
 * 1. Add extern declarations for the extension's exported functions
 * 2. Add entries to the pgl_mobile_extension_symbols[] array
 * 3. Add references in pgl_mobile_force_link_extensions()
 * 4. Compile the extension's .c file into the library (in build-mobile.sh)
 * 5. Copy the extension's SQL files to share/extension/
 *
 * OR (for modular extensions via npm packages):
 * 1. Create extension package with XCFrameworks and symbol headers
 * 2. Add extension to app.config.js
 * 3. Run expo prebuild - plugin generates pgl_extension_registry.c
 * 4. Xcode links everything together
 */

#include "postgres.h"
#include "fmgr.h"
#include <string.h>
#include "pgl_mobile_log.h"

/* Define the magic struct for extensions */
static const Pg_magic_struct pgl_mobile_magic_data = PG_MODULE_MAGIC_DATA;

/* Forward declaration for magic function */
static const Pg_magic_struct *pgl_mobile_Pg_magic_func(void);

/* Stub _PG_init for extensions that don't need initialization */
static void pgl_mobile_PG_init_stub(void) {}

/* ============================================================
 * PLPGSQL Extension (built-in)
 * ============================================================ */
extern Datum plpgsql_call_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_inline_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_validator(PG_FUNCTION_ARGS);
/*
 * Use the mobile-specific alias plpgsql_PG_init instead of _PG_init.
 * This avoids conflicts with other extensions that also define _PG_init
 * (like libpqwalreceiver) when statically linked.
 */
extern void plpgsql_PG_init(void);

/* pg_finfo functions for plpgsql */
extern const Pg_finfo_record *pg_finfo_plpgsql_call_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_inline_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_validator(void);

/* ============================================================
 * DICT_SNOWBALL Extension (built-in - Snowball stemmers for full-text search)
 * Provides language-specific word stemming for 30+ languages
 * ============================================================ */
extern Datum dsnowball_init(PG_FUNCTION_ARGS);
extern Datum dsnowball_lexize(PG_FUNCTION_ARGS);

/* pg_finfo functions for dict_snowball */
extern const Pg_finfo_record *pg_finfo_dsnowball_init(void);
extern const Pg_finfo_record *pg_finfo_dsnowball_lexize(void);

/* ============================================================
 * CITEXT Extension
 * citext uses text's I/O functions, so it only defines comparison functions
 * ============================================================ */
#ifdef PGL_EXT_CITEXT
extern Datum citext_cmp(PG_FUNCTION_ARGS);
extern Datum citext_pattern_cmp(PG_FUNCTION_ARGS);
extern Datum citext_hash(PG_FUNCTION_ARGS);
extern Datum citext_hash_extended(PG_FUNCTION_ARGS);
extern Datum citext_eq(PG_FUNCTION_ARGS);
extern Datum citext_ne(PG_FUNCTION_ARGS);
extern Datum citext_lt(PG_FUNCTION_ARGS);
extern Datum citext_le(PG_FUNCTION_ARGS);
extern Datum citext_gt(PG_FUNCTION_ARGS);
extern Datum citext_ge(PG_FUNCTION_ARGS);
extern Datum citext_pattern_lt(PG_FUNCTION_ARGS);
extern Datum citext_pattern_le(PG_FUNCTION_ARGS);
extern Datum citext_pattern_gt(PG_FUNCTION_ARGS);
extern Datum citext_pattern_ge(PG_FUNCTION_ARGS);
extern Datum citext_smaller(PG_FUNCTION_ARGS);
extern Datum citext_larger(PG_FUNCTION_ARGS);

/* pg_finfo functions - generated by PG_FUNCTION_INFO_V1 macro */
extern const Pg_finfo_record *pg_finfo_citext_cmp(void);
extern const Pg_finfo_record *pg_finfo_citext_pattern_cmp(void);
extern const Pg_finfo_record *pg_finfo_citext_hash(void);
extern const Pg_finfo_record *pg_finfo_citext_hash_extended(void);
extern const Pg_finfo_record *pg_finfo_citext_eq(void);
extern const Pg_finfo_record *pg_finfo_citext_ne(void);
extern const Pg_finfo_record *pg_finfo_citext_lt(void);
extern const Pg_finfo_record *pg_finfo_citext_le(void);
extern const Pg_finfo_record *pg_finfo_citext_gt(void);
extern const Pg_finfo_record *pg_finfo_citext_ge(void);
extern const Pg_finfo_record *pg_finfo_citext_pattern_lt(void);
extern const Pg_finfo_record *pg_finfo_citext_pattern_le(void);
extern const Pg_finfo_record *pg_finfo_citext_pattern_gt(void);
extern const Pg_finfo_record *pg_finfo_citext_pattern_ge(void);
extern const Pg_finfo_record *pg_finfo_citext_smaller(void);
extern const Pg_finfo_record *pg_finfo_citext_larger(void);
#endif /* PGL_EXT_CITEXT */

/* ============================================================
 * HSTORE Extension
 * Key-value store data type
 * ============================================================ */
#ifdef PGL_EXT_HSTORE
extern Datum hstore_in(PG_FUNCTION_ARGS);
extern Datum hstore_out(PG_FUNCTION_ARGS);
extern Datum hstore_recv(PG_FUNCTION_ARGS);
extern Datum hstore_send(PG_FUNCTION_ARGS);
extern Datum hstore_fetchval(PG_FUNCTION_ARGS);
extern Datum hstore_exists(PG_FUNCTION_ARGS);
extern Datum hstore_exists_any(PG_FUNCTION_ARGS);
extern Datum hstore_exists_all(PG_FUNCTION_ARGS);
extern Datum hstore_eq(PG_FUNCTION_ARGS);
extern Datum hstore_ne(PG_FUNCTION_ARGS);
extern Datum hstore_contains(PG_FUNCTION_ARGS);
extern Datum hstore_contained(PG_FUNCTION_ARGS);
extern Datum hstore_concat(PG_FUNCTION_ARGS);
extern Datum hstore_akeys(PG_FUNCTION_ARGS);
extern Datum hstore_avals(PG_FUNCTION_ARGS);
extern Datum hstore_skeys(PG_FUNCTION_ARGS);
extern Datum hstore_svals(PG_FUNCTION_ARGS);
extern Datum hstore_each(PG_FUNCTION_ARGS);
extern Datum hstore_to_json(PG_FUNCTION_ARGS);
extern Datum hstore_to_jsonb(PG_FUNCTION_ARGS);
extern Datum hstore_cmp(PG_FUNCTION_ARGS);
extern Datum hstore_hash(PG_FUNCTION_ARGS);
extern Datum hstore_hash_extended(PG_FUNCTION_ARGS);

extern const Pg_finfo_record *pg_finfo_hstore_in(void);
extern const Pg_finfo_record *pg_finfo_hstore_out(void);
extern const Pg_finfo_record *pg_finfo_hstore_recv(void);
extern const Pg_finfo_record *pg_finfo_hstore_send(void);
extern const Pg_finfo_record *pg_finfo_hstore_fetchval(void);
extern const Pg_finfo_record *pg_finfo_hstore_exists(void);
extern const Pg_finfo_record *pg_finfo_hstore_exists_any(void);
extern const Pg_finfo_record *pg_finfo_hstore_exists_all(void);
extern const Pg_finfo_record *pg_finfo_hstore_eq(void);
extern const Pg_finfo_record *pg_finfo_hstore_ne(void);
extern const Pg_finfo_record *pg_finfo_hstore_contains(void);
extern const Pg_finfo_record *pg_finfo_hstore_contained(void);
extern const Pg_finfo_record *pg_finfo_hstore_concat(void);
extern const Pg_finfo_record *pg_finfo_hstore_akeys(void);
extern const Pg_finfo_record *pg_finfo_hstore_avals(void);
extern const Pg_finfo_record *pg_finfo_hstore_skeys(void);
extern const Pg_finfo_record *pg_finfo_hstore_svals(void);
extern const Pg_finfo_record *pg_finfo_hstore_each(void);
extern const Pg_finfo_record *pg_finfo_hstore_to_json(void);
extern const Pg_finfo_record *pg_finfo_hstore_to_jsonb(void);
extern const Pg_finfo_record *pg_finfo_hstore_cmp(void);
extern const Pg_finfo_record *pg_finfo_hstore_hash(void);
extern const Pg_finfo_record *pg_finfo_hstore_hash_extended(void);
#endif /* PGL_EXT_HSTORE */

/* ============================================================
 * Symbol Registry
 * Maps function names to their addresses
 *
 * IMPORTANT: The __attribute__((used)) on the symbol table prevents the
 * linker from dead-stripping the extension functions. Without this, the
 * linker sees that these functions are only referenced via the pointer
 * table (not directly called) and removes them from the final binary.
 * ============================================================ */

typedef struct
{
  const char *name;
  void *address;
} pgl_mobile_symbol_entry;

/* Mark as used to prevent dead-stripping of referenced symbols */
__attribute__((used)) static const pgl_mobile_symbol_entry pgl_mobile_extension_symbols[] = {
    /* Magic function - all extensions need this */
    {"Pg_magic_func", (void *)pgl_mobile_Pg_magic_func},

    /* plpgsql - always included */
    {"plpgsql_call_handler", (void *)plpgsql_call_handler},
    {"plpgsql_inline_handler", (void *)plpgsql_inline_handler},
    {"plpgsql_validator", (void *)plpgsql_validator},
    {"_PG_init", (void *)plpgsql_PG_init},  /* Use mobile-specific alias */
    {"pg_finfo_plpgsql_call_handler", (void *)pg_finfo_plpgsql_call_handler},
    {"pg_finfo_plpgsql_inline_handler", (void *)pg_finfo_plpgsql_inline_handler},
    {"pg_finfo_plpgsql_validator", (void *)pg_finfo_plpgsql_validator},

    /* dict_snowball - always included (Snowball stemmers for full-text search) */
    {"dsnowball_init", (void *)dsnowball_init},
    {"dsnowball_lexize", (void *)dsnowball_lexize},
    {"pg_finfo_dsnowball_init", (void *)pg_finfo_dsnowball_init},
    {"pg_finfo_dsnowball_lexize", (void *)pg_finfo_dsnowball_lexize},

#ifdef PGL_EXT_CITEXT
    /* citext functions */
    {"citext_cmp", (void *)citext_cmp},
    {"citext_pattern_cmp", (void *)citext_pattern_cmp},
    {"citext_hash", (void *)citext_hash},
    {"citext_hash_extended", (void *)citext_hash_extended},
    {"citext_eq", (void *)citext_eq},
    {"citext_ne", (void *)citext_ne},
    {"citext_lt", (void *)citext_lt},
    {"citext_le", (void *)citext_le},
    {"citext_gt", (void *)citext_gt},
    {"citext_ge", (void *)citext_ge},
    {"citext_pattern_lt", (void *)citext_pattern_lt},
    {"citext_pattern_le", (void *)citext_pattern_le},
    {"citext_pattern_gt", (void *)citext_pattern_gt},
    {"citext_pattern_ge", (void *)citext_pattern_ge},
    {"citext_smaller", (void *)citext_smaller},
    {"citext_larger", (void *)citext_larger},
    {"pg_finfo_citext_cmp", (void *)pg_finfo_citext_cmp},
    {"pg_finfo_citext_pattern_cmp", (void *)pg_finfo_citext_pattern_cmp},
    {"pg_finfo_citext_hash", (void *)pg_finfo_citext_hash},
    {"pg_finfo_citext_hash_extended", (void *)pg_finfo_citext_hash_extended},
    {"pg_finfo_citext_eq", (void *)pg_finfo_citext_eq},
    {"pg_finfo_citext_ne", (void *)pg_finfo_citext_ne},
    {"pg_finfo_citext_lt", (void *)pg_finfo_citext_lt},
    {"pg_finfo_citext_le", (void *)pg_finfo_citext_le},
    {"pg_finfo_citext_gt", (void *)pg_finfo_citext_gt},
    {"pg_finfo_citext_ge", (void *)pg_finfo_citext_ge},
    {"pg_finfo_citext_pattern_lt", (void *)pg_finfo_citext_pattern_lt},
    {"pg_finfo_citext_pattern_le", (void *)pg_finfo_citext_pattern_le},
    {"pg_finfo_citext_pattern_gt", (void *)pg_finfo_citext_pattern_gt},
    {"pg_finfo_citext_pattern_ge", (void *)pg_finfo_citext_pattern_ge},
    {"pg_finfo_citext_smaller", (void *)pg_finfo_citext_smaller},
    {"pg_finfo_citext_larger", (void *)pg_finfo_citext_larger},
#endif /* PGL_EXT_CITEXT */

#ifdef PGL_EXT_HSTORE
    /* hstore functions */
    {"hstore_in", (void *)hstore_in},
    {"hstore_out", (void *)hstore_out},
    {"hstore_recv", (void *)hstore_recv},
    {"hstore_send", (void *)hstore_send},
    {"hstore_fetchval", (void *)hstore_fetchval},
    {"hstore_exists", (void *)hstore_exists},
    {"hstore_exists_any", (void *)hstore_exists_any},
    {"hstore_exists_all", (void *)hstore_exists_all},
    {"hstore_eq", (void *)hstore_eq},
    {"hstore_ne", (void *)hstore_ne},
    {"hstore_contains", (void *)hstore_contains},
    {"hstore_contained", (void *)hstore_contained},
    {"hstore_concat", (void *)hstore_concat},
    {"hstore_akeys", (void *)hstore_akeys},
    {"hstore_avals", (void *)hstore_avals},
    {"hstore_skeys", (void *)hstore_skeys},
    {"hstore_svals", (void *)hstore_svals},
    {"hstore_each", (void *)hstore_each},
    {"hstore_to_json", (void *)hstore_to_json},
    {"hstore_to_jsonb", (void *)hstore_to_jsonb},
    {"hstore_cmp", (void *)hstore_cmp},
    {"hstore_hash", (void *)hstore_hash},
    {"hstore_hash_extended", (void *)hstore_hash_extended},
    {"pg_finfo_hstore_in", (void *)pg_finfo_hstore_in},
    {"pg_finfo_hstore_out", (void *)pg_finfo_hstore_out},
    {"pg_finfo_hstore_recv", (void *)pg_finfo_hstore_recv},
    {"pg_finfo_hstore_send", (void *)pg_finfo_hstore_send},
    {"pg_finfo_hstore_fetchval", (void *)pg_finfo_hstore_fetchval},
    {"pg_finfo_hstore_exists", (void *)pg_finfo_hstore_exists},
    {"pg_finfo_hstore_exists_any", (void *)pg_finfo_hstore_exists_any},
    {"pg_finfo_hstore_exists_all", (void *)pg_finfo_hstore_exists_all},
    {"pg_finfo_hstore_eq", (void *)pg_finfo_hstore_eq},
    {"pg_finfo_hstore_ne", (void *)pg_finfo_hstore_ne},
    {"pg_finfo_hstore_contains", (void *)pg_finfo_hstore_contains},
    {"pg_finfo_hstore_contained", (void *)pg_finfo_hstore_contained},
    {"pg_finfo_hstore_concat", (void *)pg_finfo_hstore_concat},
    {"pg_finfo_hstore_akeys", (void *)pg_finfo_hstore_akeys},
    {"pg_finfo_hstore_avals", (void *)pg_finfo_hstore_avals},
    {"pg_finfo_hstore_skeys", (void *)pg_finfo_hstore_skeys},
    {"pg_finfo_hstore_svals", (void *)pg_finfo_hstore_svals},
    {"pg_finfo_hstore_each", (void *)pg_finfo_hstore_each},
    {"pg_finfo_hstore_to_json", (void *)pg_finfo_hstore_to_json},
    {"pg_finfo_hstore_to_jsonb", (void *)pg_finfo_hstore_to_jsonb},
    {"pg_finfo_hstore_cmp", (void *)pg_finfo_hstore_cmp},
    {"pg_finfo_hstore_hash", (void *)pg_finfo_hstore_hash},
    {"pg_finfo_hstore_hash_extended", (void *)pg_finfo_hstore_hash_extended},
#endif /* PGL_EXT_HSTORE */

    /* End marker */
    {NULL, NULL}};

/* Magic function implementation */
static const Pg_magic_struct *
pgl_mobile_Pg_magic_func(void)
{
  return &pgl_mobile_magic_data;
}

/* ============================================================
 * Public API Implementation
 * ============================================================ */

/* Forward declarations for external extension hooks (weak symbols - fallback) */
extern void *pgl_external_lookup_symbol(const char *symbol) __attribute__((weak));
extern bool pgl_external_is_builtin_library(const char *libname) __attribute__((weak));
extern void pgl_external_force_link_extensions(void) __attribute__((weak));

/* ============================================================
 * Registered Extension Hooks (Function Pointer Pattern)
 *
 * This pattern bypasses weak symbol linking issues by using explicit
 * function pointer registration. Extensions call pgl_register_*()
 * during initialization (via __attribute__((constructor))).
 *
 * IMPORTANT: Supports MULTIPLE extensions (e.g., PostGIS + pgsodium).
 * Each extension registers its own lookup/is_builtin/force_link functions.
 * We store them in arrays and iterate through all of them.
 * ============================================================ */
typedef void *(*pgl_lookup_fn)(const char *symbol);
typedef bool (*pgl_is_builtin_fn)(const char *libname);
typedef void (*pgl_force_link_fn)(void);

/* Maximum number of external extensions that can be registered */
#define PGL_MAX_EXTERNAL_EXTENSIONS 16

/* Registered function pointer arrays (supports multiple extensions) */
static pgl_lookup_fn pgl_registered_lookups[PGL_MAX_EXTERNAL_EXTENSIONS];
static pgl_is_builtin_fn pgl_registered_is_builtins[PGL_MAX_EXTERNAL_EXTENSIONS];
static pgl_force_link_fn pgl_registered_force_links[PGL_MAX_EXTERNAL_EXTENSIONS];
static int pgl_num_registered_lookups = 0;
static int pgl_num_registered_is_builtins = 0;
static int pgl_num_registered_force_links = 0;

/* Public registration functions - called by generated extension registries */
void pgl_register_external_lookup(pgl_lookup_fn fn)
{
  if (pgl_num_registered_lookups >= PGL_MAX_EXTERNAL_EXTENSIONS)
  {
    PGL_LOG_FMT("WARNING: Cannot register lookup function %p - max extensions (%d) reached",
                (void *)fn, PGL_MAX_EXTERNAL_EXTENSIONS);
    return;
  }
  PGL_LOG_FMT("Registering external lookup function [%d]: %p",
              pgl_num_registered_lookups, (void *)fn);
  pgl_registered_lookups[pgl_num_registered_lookups++] = fn;
}

void pgl_register_external_is_builtin(pgl_is_builtin_fn fn)
{
  if (pgl_num_registered_is_builtins >= PGL_MAX_EXTERNAL_EXTENSIONS)
  {
    PGL_LOG_FMT("WARNING: Cannot register is_builtin function %p - max extensions (%d) reached",
                (void *)fn, PGL_MAX_EXTERNAL_EXTENSIONS);
    return;
  }
  PGL_LOG_FMT("Registering external is_builtin function [%d]: %p",
              pgl_num_registered_is_builtins, (void *)fn);
  pgl_registered_is_builtins[pgl_num_registered_is_builtins++] = fn;
}

void pgl_register_external_force_link(pgl_force_link_fn fn)
{
  if (pgl_num_registered_force_links >= PGL_MAX_EXTERNAL_EXTENSIONS)
  {
    PGL_LOG_FMT("WARNING: Cannot register force_link function %p - max extensions (%d) reached",
                (void *)fn, PGL_MAX_EXTERNAL_EXTENSIONS);
    return;
  }
  PGL_LOG_FMT("Registering external force_link function [%d]: %p",
              pgl_num_registered_force_links, (void *)fn);
  pgl_registered_force_links[pgl_num_registered_force_links++] = fn;
}

/*
 * Lookup a symbol in the static extension registry.
 * First checks built-in extensions, then external extension registries.
 */
void *
pgl_mobile_lookup_symbol(const char *symbol)
{
  const pgl_mobile_symbol_entry *entry;
  void *result;

  if (symbol == NULL)
    return NULL;

  /* First, check built-in extensions */
  for (entry = pgl_mobile_extension_symbols; entry->name != NULL; entry++)
  {
    if (strcmp(entry->name, symbol) == 0)
      return entry->address;
  }

  /* Then, check all registered external extension functions (priority over weak symbols) */
  for (int i = 0; i < pgl_num_registered_lookups; i++)
  {
    if (pgl_registered_lookups[i] != NULL)
    {
      result = pgl_registered_lookups[i](symbol);
      if (result != NULL)
        return result;
    }
  }

  /* Fallback: check weak external extension registries */
  if (pgl_external_lookup_symbol != NULL)
  {
    result = pgl_external_lookup_symbol(symbol);
    if (result != NULL)
      return result;
  }

  return NULL;
}

/*
 * Check if a library name refers to a built-in extension.
 * We match against known extension library names, then check external registries.
 */
bool pgl_mobile_is_builtin_library(const char *libname)
{
  if (libname == NULL)
    return false;

  /* Check for plpgsql (always built-in) */
  if (strstr(libname, "plpgsql") != NULL)
    return true;

  /* Check for dict_snowball (always built-in - Snowball stemmers) */
  if (strstr(libname, "snowball") != NULL || strstr(libname, "dict_snowball") != NULL)
    return true;

#ifdef PGL_EXT_CITEXT
  if (strstr(libname, "citext") != NULL)
    return true;
#endif

#ifdef PGL_EXT_HSTORE
  if (strstr(libname, "hstore") != NULL)
    return true;
#endif

  /* Check all registered external extension functions (priority over weak symbols) */
  for (int i = 0; i < pgl_num_registered_is_builtins; i++)
  {
    if (pgl_registered_is_builtins[i] != NULL && pgl_registered_is_builtins[i](libname))
      return true;
  }

  /* Fallback: check weak external extension registries */
  if (pgl_external_is_builtin_library != NULL && pgl_external_is_builtin_library(libname))
    return true;

  return false;
}

/* ============================================================
 * Force Link Function
 *
 * This function creates explicit references to all extension functions.
 * It MUST be called from somewhere in the initialization path to ensure
 * the linker includes the extension object files from the static archive.
 *
 * The (void) casts prevent "unused value" warnings while still creating
 * the necessary symbol references for the linker.
 * ============================================================ */
static volatile void *_pgl_force_link_sink;

/* Track if plpgsql has been initialized (to avoid double-init) */
static bool pgl_plpgsql_initialized = false;

void pgl_mobile_force_link_extensions(void)
{
  /* plpgsql - always included */
  _pgl_force_link_sink = (void *)plpgsql_call_handler;
  _pgl_force_link_sink = (void *)plpgsql_inline_handler;
  _pgl_force_link_sink = (void *)plpgsql_validator;
  _pgl_force_link_sink = (void *)plpgsql_PG_init;  /* Use mobile-specific alias */
  _pgl_force_link_sink = (void *)pg_finfo_plpgsql_call_handler;
  _pgl_force_link_sink = (void *)pg_finfo_plpgsql_inline_handler;
  _pgl_force_link_sink = (void *)pg_finfo_plpgsql_validator;

  /* dict_snowball - always included */
  _pgl_force_link_sink = (void *)dsnowball_init;
  _pgl_force_link_sink = (void *)dsnowball_lexize;
  _pgl_force_link_sink = (void *)pg_finfo_dsnowball_init;
  _pgl_force_link_sink = (void *)pg_finfo_dsnowball_lexize;

#ifdef PGL_EXT_CITEXT
  _pgl_force_link_sink = (void *)citext_cmp;
  _pgl_force_link_sink = (void *)citext_eq;
  _pgl_force_link_sink = (void *)citext_ne;
  _pgl_force_link_sink = (void *)citext_lt;
  _pgl_force_link_sink = (void *)citext_le;
  _pgl_force_link_sink = (void *)citext_gt;
  _pgl_force_link_sink = (void *)citext_ge;
  _pgl_force_link_sink = (void *)citext_hash;
  _pgl_force_link_sink = (void *)pg_finfo_citext_eq;
#endif

#ifdef PGL_EXT_HSTORE
  _pgl_force_link_sink = (void *)hstore_in;
  _pgl_force_link_sink = (void *)hstore_out;
  _pgl_force_link_sink = (void *)pg_finfo_hstore_in;
#endif

  /* Call all registered external extension force link functions */
  for (int i = 0; i < pgl_num_registered_force_links; i++)
  {
    if (pgl_registered_force_links[i] != NULL)
    {
      pgl_registered_force_links[i]();
    }
  }

  /* Fallback: call weak external extension force link if available */
  if (pgl_external_force_link_extensions != NULL)
  {
    pgl_external_force_link_extensions();
  }

  PGL_LOG("pgl_mobile_force_link_extensions() called - extensions linked");
}

/* ============================================================
 * Extension Initialization
 *
 * CRITICAL: This function must be called AFTER PostgreSQL is initialized
 * but BEFORE any PL/pgSQL functions are used. Without this, the
 * plpgsql_HashTable will be NULL and hash_search() will crash.
 *
 * The issue is that on iOS devices, the lazy initialization in
 * load_external_function() may not trigger correctly, leaving
 * plpgsql_HashTable uninitialized.
 * ============================================================ */
void pgl_mobile_init_extensions(void)
{
  PGL_LOG("pgl_mobile_init_extensions() called - initializing extensions...");

  /*
   * Initialize plpgsql - this MUST be called before any PL/pgSQL functions
   * can be used. It sets up the hash table that stores compiled functions.
   *
   * Without this, plpgsql_compile() will call hash_search(NULL, ...) and crash.
   */
  if (!pgl_plpgsql_initialized)
  {
    PGL_LOG("Initializing plpgsql via plpgsql_PG_init()...");
    plpgsql_PG_init();
    pgl_plpgsql_initialized = true;
    PGL_LOG("plpgsql_PG_init() completed successfully");
  }
  else
  {
    PGL_LOG("plpgsql already initialized, skipping");
  }

  /* Initialize external extensions if registered */
  /* Note: External extensions may need their own _PG_init calls */
  
  PGL_LOG("pgl_mobile_init_extensions() completed");
}

/* ============================================================
 * External Extension Registry Hooks
 *
 * These weak functions provide hooks for external extension packages.
 * When an app includes extensions like @react-native-pglite/postgis,
 * the Expo config plugin generates a pgl_extension_registry.c file
 * that provides strong implementations of these functions.
 *
 * The __attribute__((weak)) allows these to be overridden at link time.
 * ============================================================ */

/*
 * Weak default: lookup symbol in external registries.
 * Returns NULL if no external registries or symbol not found.
 * Override this to add extension symbol lookups.
 */
__attribute__((weak)) void *pgl_external_lookup_symbol(const char *symbol)
{
  /* Default: no external extensions */
  return NULL;
}

/*
 * Weak default: check if library is an external extension.
 * Returns false if no external extensions or library not recognized.
 * Override this to add extension library checks.
 */
__attribute__((weak)) bool pgl_external_is_builtin_library(const char *libname)
{
  /* Default: no external extensions */
  return false;
}

/*
 * Weak default: force link external extension symbols.
 * Does nothing if no external extensions.
 * Override this to add force link references for extension functions.
 */
__attribute__((weak)) void pgl_external_force_link_extensions(void)
{
  /* Default: no external extensions to link */
}

/*
 * Weak default: get count of external extension symbol entries.
 * Returns 0 if no external extensions.
 */
__attribute__((weak)) int pgl_external_get_symbol_count(void)
{
  return 0;
}
